### PR TITLE
Removing existing AWS detections, and start GCP scaffolding

### PR DESCRIPTION
**Pull request by RichardoC**

### CODE REVIEW

**Comment by orf** [comment]
I would love for this to be included in this repository as well as AWS keys - it seems redundant to do a very similar thing in two repositories, but as a FYI I’ve been detecting GCP secrets via a different mechanism (GitHub secret scanning).

 So far there are 280 found: https://github.com/pypi-data/secrets

**Comment by RichardoC** [comment]
If I can get it working, happy to contribute it! This PR was raised by mistake and it'll likely be a while until I have anything worth discussing because I'm new to rust

**Comment by orf** [comment]
Ok, no problem! Good luck, I’m a bit new to Rust as well so I hope my code doesn’t put you off 😂

**Comment by RichardoC** [comment]
I'm interested in adding scanning for the other types listed [here](https://github.com/odomojuli/RegExAPI) but it sounds like you're already doing it somewhere? Keen to avoid duplication! 

It seems I found a few things last night but made a mistake in my changes to your code so didn't capture them

**Comment by orf** [comment]
I realised after making this repository that the approach wasn’t scalable. Scanning packages is inherently “one-way”, which means adjusting your regex or adding a new type of secret requires a complete re-scan.

I shifted my approach to instead committing every bit of code in pypi to GitHub. You can see the repositories under this organisation (for example https://github.com/pypi-data/pypi-code-132).

This is has two advantages: GitHub themselves can take care of managing the secret scanning  patterns, and as new ones are added previously-committed code is automatically scanned.

Git compresses all this exceptionally well, so the entire set of pypi Python code could fit in about 120gb, which also allows rapid local experimentation and iteration.

I’m currently travelling around Japan until the end of the month, so this work has taken a hiatus, but the approach is sound and it’s working.

However I don’t want to put you off your idea (and learning rust), and this repository will still be around, so we can definitely add GCP secret scanning to it.

**Pull request closed without merging**
